### PR TITLE
Clickcard

### PR DESCRIPTION
**Pull request by swissbusybee**
Added the image of the card to be clickable in the search, index and my adventure pages.  Had trouble adding the clickable event to the whole card so the click is on the title and image.

### CODE REVIEW

**Comment by joyceykao** [comment]
Hi @swissbusybee, I implemented clickable cards with my mister rails index cards recently. Here's a snippet of the code. Maybe it helps.
`<div class="cards">
    <% @cocktails.each do |cocktail| %>
      <%= link_to cocktail_path(cocktail), id: 'link' do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(cocktail.photo.key) %>')" >
          <%= cocktail.name  %>
        </div>
      <% end %>
      <% end %>
    </div>`

**Comment by swissbusybee** [comment]
Thanks Joyce.  I tried your code but it results in the same functionality I had before.  Maybe I am missing something?

**Comment by joyceykao** [comment]
@swissbusybee, works now. You can pull, check the code, and merge if it checks out with you.

UPDATE: I just realized I forgot the cards on my_adventures. I'll fix that real quickly and push it.

**Comment by joyceykao** [comment]
@swissbusybee The my_adventure index page is not as straightforward because making the card clickable is a bit more of a nightmare in the html with all the div's and the edit/delete icons. The card formatting gets screwed...

**Comment by swissbusybee** [comment]
Thanks for figuring it out!  Really appreciate it. : )

**Pull request merged**
