### PR TITLE
My adv clickcard frontend

### PR DESCRIPTION
**Pull request by joyceykao**
Fixed the text, but having issues positioning the icon on the saved adventures card.

### CODE REVIEW

**Comment by joyceykao** [comment]
I got it!!! I pinned that freaking trashcan on the freaking card for saved adventures!!!

Will propagate the style and changes over to 'reviews' and my adventures tomorrow when less concussion-y.
Screen Shot 2020-05-25 at 7 43 41 PM

**Comment by joyceykao** [comment]
Finished formatting cards for review and my mini adventures
Screen Shot 2020-05-25 at 11 00 05 PM

**Comment by joyceykao** [comment]
Uhh...I just realized in reformatting the cards ton my_adventures, I broke the cards on the front and search pages. WAIT TO MERGE. I will fix it...

**Comment by joyceykao** [comment]
@swissbusybee @epalander I fixed the cards on all the pages. It's not absolutely perfectly centered, but close enough?

**Comment by swissbusybee** [comment]
Close enough for now. Maybe we can tinker with it in the future. Thanks for the hard work!

**Pull request merged**
